#!/bin/bash

cd $OPENSHIFT_REPO_DIR

mkdir -p "$OPENSHIFT_DATA_DIR"node_modules

ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules

npm install --loglevel error

mkdir -p ${OPENSHIFT_DATA_DIR}messages
rm -rf ${OPENSHIFT_DATA_DIR}messages/messages.tar.gz
