#!/bin/bash
#mkdir -p ${OPENSHIFT_DATA_DIR}messages
#cd ${OPENSHIFT_DATA_DIR}messages
cd messages
rm -rf core

tar xzf messages.tar.gz

#cd $OPENSHIFT_REPO_DIR
cd ..
node parse.js

#rm -rf messages.tar.gz
